#!/bin/sh
set -e

MODULE_VERSION="2.0.0"
MODULE_NAME="aleqfs"

if command -v dkms >/dev/null 2>&1; then
    dkms remove -m ${MODULE_NAME} -v ${MODULE_VERSION} --all 2>/dev/null || true
fi
rm -rf /usr/src/${MODULE_NAME}-${MODULE_VERSION} 2>/dev/null || true
exit 0
